#!/bin/bash
# GGEN Device Validation - Linked Text-Flow Manual Test Guide
# Since ADB cannot simulate keyboard input or multi-touch gestures,
# this script documents the manual test procedure for linked text-flow.

echo "=========================================="
echo "Linked Text-Flow Manual Test Procedure"
echo "Date: $(date)"
echo "Device: Redmi Turbo 4 Pro"
echo "=========================================="
echo ""

echo "PREREQUISITES:"
echo "- App installed with debug logging enabled"
echo "- Basic shape/text creation working (verified)"
echo ""

echo "TEST PROCEDURE:"
echo ""
echo "1. LAUNCH APP"
echo "   \$ adb shell am start -n com.example.ggen/com.example.ggen_app.MainActivity"
echo ""

echo "2. CREATE FIRST TEXT FRAME"
echo "   - Tap Text tool (left rail, 3rd icon)"
echo "   - Tap canvas center"
echo "   - Type: 'Hello World'"
echo "   - Confirm (keyboard enter or done button)"
echo "   Expected: node_add_text event logged"
echo ""

echo "3. CREATE SECOND TEXT FRAME"
echo "   - Tap Text tool again"
echo "   - Tap canvas at different position"
echo "   - Type: 'This continues in another frame'"
echo "   - Confirm"
echo ""

echo "4. OPEN INSPECTOR FOR FIRST FRAME"
echo "   - Tap on first text frame to select it"
echo "   - Inspector panel should appear on right side"
echo "   - Scroll to find 'Text flow' section"
echo "   Expected: Section shows 'Flows into: [second frame]' or similar"
echo ""

echo "5. CONFIGURE LINKED FLOW"
echo "   - In Text flow section, select second frame as successor"
echo "   - Tap 'Link' or equivalent button"
echo "   Expected: Blue continuation indicator appears on first frame"
echo ""

echo "6. ADD MORE TEXT TO FIRST FRAME"
echo "   - Tap first frame to select"
echo "   - Edit text in inspector or directly"
echo "   - Add overflow text (type more than fits)"
echo "   Expected: Excess text flows into second frame"
echo ""

echo "7. TEST UNLINK"
echo "   - Select first frame"
echo "   - In Text flow section, tap 'Unlink'"
echo "   Expected: Continuation indicator disappears"
echo ""

echo "8. MULTI-COLUMN CONFIGURATION"
echo "   - Select any text frame"
echo "   - Open Columns sheet (bottom panel)"
echo "   - Set columns to 2 or 3"
echo "   - Adjust gutter value"
echo "   - Apply changes"
echo "   Expected: Text reflows into multiple columns"
echo ""

echo "9. SAVE & RESTART"
echo "   - Save project via More menu"
echo "   - Force stop app"
echo "   - Restart app"
echo "   Expected: Project restored with linked text frames intact"
echo ""

echo "DEBUG LOG COMMANDS:"
echo ""
echo "# Pull current log:"
echo "\$ adb shell run-as com.example.ggen cat app_flutter/debug_log.jsonl"
echo ""
echo "# Filter for text-related events:"
echo "\$ adb shell run-as com.example.ggen cat app_flutter/debug_log.jsonl | grep -E '(text|flow|link|column)'"
echo ""
echo "# Watch for real-time events:"
echo "\$ adb logcat -s DebugLogStore:I"
echo ""

echo "EXPECTED EVENTS:"
echo "- node_add_text: Text frame created"
echo "- inspector_text_edit: Text modified"
echo "- text_flow_link: Frames linked"
echo "- text_flow_unlink: Frames unlinked"
echo "- column_layout_change: Columns modified"
echo "- project_save: Project saved with linked frames"
echo "- project_restore: Project restored"
echo ""

echo "SUCCESS CRITERIA:"
echo "1. Multiple text frames can be created"
echo "2. Frames can be linked via inspector"
echo "3. Text flows from one frame to next"
echo "4. Multi-column layout works"
echo "5. Links persist across save/restart"
echo "6. No crashes or errors in log"
echo ""
