#!/usr/bin/env python3
"""Normalize the generated Android wrapper identity to "ggen".

The manual APK workflow generates a temporary Android wrapper with
`flutter create --project-name=ggen_app`, which would install the app
with the launcher label "ggen_app" and process name
"com.example.ggen_app". This script rewrites the generated wrapper so
the device-facing app identity is exactly "ggen":

- AndroidManifest.xml: android:label -> "ggen"
- AndroidManifest.xml: meta-data ggen_app_version -> full pubspec version
  (injected via --version flag; CI passes the resolved version)
- build.gradle(.kts):  applicationId -> "com.example.ggen"

The Dart package identifier (pubspec name "ggen_app") and the
Kotlin/namespace stay internal and are not user-visible; the launcher
label and the Android process name (applicationId) are the user-facing
identity and are what this script normalizes.

Idempotent: re-running on an already-normalized wrapper is a no-op.
Fails loudly when a pattern is missing, so CI never silently ships an
APK with the wrong name.

Usage: prepare_android_identity.py <path-to-android-dir> [--version VERSION]
       The --version flag injects the full pubspec version (e.g. 0.1.0+71)
       as a <meta-data> tag so the app can display the build identifier.
"""

import re
import sys
from pathlib import Path

APP_LABEL = "ggen"
APPLICATION_ID = "com.example.ggen"

_LABEL_RE = re.compile(r'(<application\b[^>]*\bandroid:label=")[^"]*(")')
_APPLICATION_ID_RE = re.compile(
    r'(applicationId\s*(?:=\s*)?")[^"]*(")'
)
_META_DATA_RE = re.compile(
    r'(<meta-data\s+android:name="ggen_app_version"\s+android:value=")[^"]*(")'
)
_APPLICATION_CLOSE_RE = re.compile(r'(</application>)')


def normalize_manifest(manifest: Path, version: str | None) -> bool:
    text = manifest.read_text(encoding="utf-8")
    changed = False

    # Fix label
    updated, count = _LABEL_RE.subn(rf"\g<1>{APP_LABEL}\g<2>", text)
    if count == 0:
        raise SystemExit(
            f"prepare_android_identity: no android:label found in "
            f"{manifest}; refusing to ship an unnamed APK."
        )
    if updated != text:
        text = updated
        changed = True
        print(f"  manifest label -> {APP_LABEL} ({manifest})")

    # Inject or update full version meta-data (only if version provided)
    if version is not None:
        updated, count = _META_DATA_RE.subn(
            rf"\g<1>{version}\g<2>", text
        )
        if count == 0:
            # Inject before </application>
            insert = (
                f'        <meta-data\n'
                f'            android:name="ggen_app_version"\n'
                f'            android:value="{version}" />\n'
            )
            updated = _APPLICATION_CLOSE_RE.sub(insert + "\n</application>", text)
            if updated == text:
                raise SystemExit(
                    f"prepare_android_identity: could not inject "
                    f"ggen_app_version meta-data into {manifest}."
                )
            print(f"  manifest meta-data -> ggen_app_version={version}")
            changed = True
        elif updated != text:
            print(f"  manifest meta-data updated -> ggen_app_version={version}")
            changed = True
        text = updated

    if changed:
        manifest.write_text(text, encoding="utf-8")
    return changed


def write_version_file(repo_root: Path, version: str | None) -> bool:
    """Write a Dart-accessible version constant file into the lib directory."""
    if version is None:
        return False
    version_file = repo_root / "lib" / "version.dart"
    content = f'// Auto-generated by prepare_android_identity.py — do not edit\n'
    content += f'// Version injected during CI build.\n'
    content += f'const String ggenBuildVersion = "{version}";\n'
    if version_file.exists():
        existing = version_file.read_text(encoding="utf-8")
        if existing.strip() == content.strip():
            return False
    version_file.write_text(content, encoding="utf-8")
    print(f"  wrote version.dart -> {version} ({version_file})")
    return True


def normalize_build_file(build_file: Path) -> bool:
    if not build_file.exists():
        return False
    text = build_file.read_text(encoding="utf-8")
    updated, count = _APPLICATION_ID_RE.subn(
        rf"\g<1>{APPLICATION_ID}\g<2>", text
    )
    if count == 0:
        raise SystemExit(
            f"prepare_android_identity: no applicationId found in "
            f"{build_file}; refusing to ship an APK with a wrong process name."
        )
    if updated != text:
        build_file.write_text(updated, encoding="utf-8")
        print(f"  applicationId -> {APPLICATION_ID} ({build_file})")
    return updated != text


def main() -> None:
    version = None
    args = sys.argv[1:]

    # Parse optional --version flag
    if len(args) >= 2 and args[-2] == "--version":
        version = args[-1]
        args = args[:-2]
    elif len(args) >= 1 and args[0].startswith("--version="):
        version = args[0].split("=", 1)[1]
        args = args[1:]

    if len(args) != 1:
        raise SystemExit(
            "usage: prepare_android_identity.py <path-to-android-dir> "
            "[--version VERSION]"
        )

    android_dir = Path(args[0])
    manifest = android_dir / "app" / "src" / "main" / "AndroidManifest.xml"
    if not manifest.exists():
        raise SystemExit(
            f"prepare_android_identity: {manifest} not found; was the "
            f"Android wrapper generated?"
        )

    changed = False
    changed |= normalize_manifest(manifest, version)
    for name in ("build.gradle", "build.gradle.kts"):
        changed |= normalize_build_file(android_dir / "app" / name)
    changed |= write_version_file(android_dir.parent.parent, version)

    if changed:
        print("Android app identity normalized to ggen.")
    else:
        print("Android app identity already ggen; no changes.")


if __name__ == "__main__":
    main()
